### ISSUE TITLE
MSVCP140D.dll is missing

### ISSUE THREAD

**Issue by NekoJonez** [thekovic/Indy3DModInstaller#2]
![image](https://github.com/user-attachments/assets/daf465bf-62ca-4063-9067-b4f656628907)

Sorry for the Dutch error message, but the gist is, that MSVCP140D.dll is missing. The error comes from gobext.exe ... So, don't know if it's an issue with the tool.
I looked it up online, and it's recommended to download and install this: https://www.microsoft.com/en-gb/download/details.aspx?id=48145 ... Yet, I have already a newer version installed... D:

**Comment by NekoJonez** [comment]
I redownloaded gobext.exe and replaced it and it looks like that fixes it.

**Comment by thekovic** [comment]
I did some research and it suggests that the reason it doesn't work for you is because I shipped a Debug build of gobext.exe which requires a Debug version of the runtime which the normal installer doesn't ship. I updated the release with a new build of gobext.exe. See if it works for you @NekoJonez

**Comment by NekoJonez** [comment]
Yup, it works now. :)

**Comment by thekovic** [comment]
Okay, good to know. Btw, the pull request in the Urgon repo was merged so as soon as they make a new release, I can stop bundling a custom build of gobext with Indy3DModInstaller.

**Comment by NekoJonez** [comment]
You might have noticed that I added a comment in my script. If a new version with your code is released, I'll refactor my version since it makes the process a LOOOOOOT easier :D.
I can't write C, so nice catch there :)
